run script simplifications

diff --git a/tools/githooks/pre-commit b/tools/githooks/pre-commit
--- a/tools/githooks/pre-commit
+++ b/tools/githooks/pre-commit
@@ -1,9 +1,8 @@
 #!/bin/bash
 
-# Called by `git push` after it has checked the remote status,
-# but before anything has been pushed.
-# If this script exits with a non-zero status, nothing will be pushed.
-#
+# Install this file as a pre-commit hook,
+# If this script exits with a non-zero status, commit will not proceed.
+
 # This script is run OUTSIDE OF DOCKER.
 # Install dependencies on the dev machine:
 #
@@ -11,8 +10,6 @@
 
 
 set -e
-remote="$1"
-url="$2"
 
 thisfile="${BASH_SOURCE[0]}"
 thisdir="$(cd "$(dirname "${thisfile}")"; pwd)"
@@ -22,6 +19,8 @@ if [[ "$(basename "${thisdir}")" != .githooks ]]; then
     # script should have ensured that `pwd` is the repo's root directory.
     rootdir="$(pwd)"
 else
+    # In this case, the script is in folder `.githooks/`, so we go
+    # one level up into the root directory of the repo.
     rootdir="$(dirname "${thisdir}")"
 fi
 
@@ -41,6 +40,8 @@ TESTS="${rootdir}/tests"
 
 status=0
 
+
+
 # `black -S`: do not change between single/double quotes; leave them as is.
 # changed=$(python3 -m black --check -q -S "${SRC}" "${TESTS}"; echo $?)
 changed=$(python3 -m ruff format --check -q "${SRC}" "${TESTS}" >/dev/null 2>&1; echo $?)
@@ -50,13 +51,13 @@ if [[ "${changed}" != 0 ]]; then
     echo ==\> -\> -\> Formatting code by \`ruff\` ...
     python3 -m ruff format "${SRC}" "${TESTS}"
     echo
-    echo Please add the reformatted files in a new commit and push again.
+    echo Please add the reformatted files and commit again.
     echo
     status=1
-    # We do not auto commit the changes here.
+    # We do not commit the changes here by `git add -u`.
     # It's hard to take care of all scenarios, e.g. there may be a file
-    # that was changed (unrelated to formatting) but we are not ready to
-    # commit and push it yet, hence the file was not included in the last commit.
+    # that was changed (unrelated to formatting) but was intentionally not added to the commit,
+    # while `git add -u` would add it to the commit.
 fi
 
 
@@ -68,10 +69,19 @@ if [[ "${changed}" == 1 ]]; then
     echo ==\> -\> -\> Fixing some issues by \`ruff --fix\` ...
     python3 -m ruff check --no-cache --fix "${SRC}" "${TESTS}"
     echo
-    echo Please examine the issues reported/fixed by \`ruff\` and commit/push again.
+    echo Please examine the issues reported/fixed by \`ruff\`; if all is good, please add them and commit again.
     echo
     status=1
 fi
+
+
+
+# echo
+# echo --- running mypy ---
+# echo
+# # python -m mypy --show-error-codes --disable-error-code import ${SRC} || true
+# python3 -m mypy ${SRC} || true  # MyPy errors do not halt this script
+
 
 
 exit "${status}"
diff --git a/tools/pip-based/run b/tools/pip-based/run
--- a/tools/pip-based/run
+++ b/tools/pip-based/run
@@ -32,6 +32,28 @@
 
 set -e
 
+
+# In the real workflow, `$PARENT` is already defined in the script that calls the current script.
+# Here we allow it to be missing so that the current script can be invoked directly
+# during development and debugging of this script.
+PARENT="${PARENT:-zppz/py3:24.12.16}"
+
+if [[ $(uname -s) == Darwin && $(uname -p) == arm ]]; then
+    # On Mac, we do not pull the parent image from a remote registry,
+    # but rather require a locally-built one to exist, because
+    # the remotely-stored images are for arm64 architecture only.
+    if [[ $(docker images -q ${PARENT}) == '' ]]; then
+        >&2 echo "Cannot find the parent image '${PARENT}'."
+        exit 1
+    fi
+    if [[ $(docker image inspect -f "{{.Architecture}}" ${PARENT}) != arm64 ]]; then
+        >&2 echo "The parent image '${PARENT}' on this machine is not optimized for the CPU architecture."
+        exit 1
+    fi
+fi
+echo "Parent image: ${PARENT}"
+
+
 thisdir="$(cd $( pwd ) && pwd)"  # full path; do not use `${BASH_SOURCE[0]}` b/c this script is not invoked directly.
 echo "Work directory: ${thisdir}"
 
@@ -66,42 +88,12 @@ branch=$(cat "${thisdir}/.git/HEAD")
 GITBRANCH=${branch##*refs/heads/}  # remove the longest substr from front
 echo "Branch: ${GITBRANCH}"
 
-if [[ "${GITBRANCH}" == release ]]; then
-    rm -rf "${thisdir}/dist"
-fi
-
-
-# In the real workflow, `$TINY`, `$MINI`, and `$PARENT` are already defined in the script that calls the current script.
-# Here we allow them to be missing so that the current script can be invoked directly
-# during development and debugging of this script.
-TINY="${TINY:-zppz/tiny:22.12.11}"
-cmd_find="$(docker run --rm ${TINY} cat /tools/find-image)"
-
-if [[ -z "${MINI}" ]]; then
-    MINI="$(bash -c "${cmd_find}" -- zppz/mini)"
-fi
-
-PARENT="${PARENT:-zppz/py3}"
-PARENT="$(bash -c "${cmd_find}" -- ${PARENT})"  # find the latest version.
-if [[ $(uname -s) == Darwin && $(uname -p) == arm ]]; then
-    if [[ $(docker images -q ${PARENT}) == '' ]]; then
-        >&2 echo "Cannot find the parent image '${PARENT}'."
-        exit 1
-    fi
-    if [[ $(docker image inspect -f "{{.Architecture}}" ${PARENT}) != arm64 ]]; then
-        >&2 echo "The parent image '${PARENT}' on this machine is not optimized for the CPU architecture."
-        exit 1
-    fi
-fi
-echo "Parent image: ${PARENT}"
 
 DOCKER_SRCDIR=/tmp/src
 # Copy project repo to this location in the image.
 
 rm -f "${thisdir}"/Dockerfile
 cat <<EOF >"${thisdir}"/Dockerfile
-FROM ${MINI} as mini-image
-
 FROM ${PARENT}
 USER root
 
@@ -110,10 +102,10 @@ ENV PARENT_IMAGE=${PARENT}
 # If the repo needs non-Python dependencies, will need a mechanism
 # to insert a block to install other things, or use user-defined Dockerfile.
 
-
 # Install the package of the current repo along with all its required and optional
-# dependencies. Then, uninstall the project package itself and remove the source code from the image,
-# leaving the dependencies in place.
+# dependencies. Then, uninstall the project package itself,
+# leaving the dependencies in place. The source code is left in the image in order to run tests;
+# otherwise it will be largely forgotten.
 # Dev and test within the container will use volume-mapped live code.
 
 ARG DOCKER_SRCDIR
@@ -123,9 +115,6 @@ ARG pyproj="${DOCKER_SRCDIR}/pyproject.toml"
 RUN extras=\$(python -c "import toml; print(','.join(toml.load('\${pyproj}')['project']['optional-dependencies'].keys()))") \\
     && pip-install ${DOCKER_SRCDIR}/[\${extras}] \\
     && python -m pip uninstall -y \$(python -c "import toml; print(toml.load('\${pyproj}')['project']['name'])")
-
-COPY --from=mini-image /tools/run-tests /usr/local/bin
-RUN chmod +x /usr/local/bin/run-tests
 
 USER docker-user
 EOF
@@ -142,9 +131,11 @@ if [[ "${GITBRANCH}" == main || "${GITBRANCH}" == master || "${GITBRANCH}" == re
         -e PROJ="${PROJ}" \
         --workdir="${DOCKER_SRCDIR}" \
         -e PYTHONPATH="${DOCKER_SRCDIR}"/src \
-        ${PROJ}:dev run-tests
+        ${PROJ}:dev py.test "src/${PKG}" "tests"
 
     if [[ "${GITBRANCH}" == release ]]; then
+        rm -rf "${thisdir}/dist"
+
         docker rm "${PROJ}-release" &>/dev/null || true
         docker run \
             --workdir="${DOCKER_SRCDIR}" \
@@ -161,7 +152,7 @@ if [[ "${GITBRANCH}" == main || "${GITBRANCH}" == master || "${GITBRANCH}" == re
 else
     # Take a free ride to config githooks
     git config --local core.hooksPath "${thisdir}/.githooks/"
-    chmod +x "${thisdir}/.githooks/pre-push"
+    chmod +x "${thisdir}/.githooks/pre-commit" | (>&2 echo 'pre-commit file is missing' && exit 1)
 
     rm -f "${thisdir}"/Dockerfile
     run-docker ${PROJ}:dev
